In [1]:
import numpy as np

In [18]:
class ProbMat:
    """Storing and managing probability matrices."""

    # init a probability matrix - create the matrix itself
    def __init__(self, x = 5, y = 8):
        """ Init a matrix with the given dimensions. """

        self.matrix = [[0.0 for col in range(x+2)] for row in range(y)]
        for i in range(2,len(self.matrix)):
            for j in range(1,len(self.matrix[i])-1):
                self.matrix[i][j] = 1.0/x
        self.matrix[0][(x+2)/2] = 1.0
        for i in range((x+2)/2-1, (x+2)/2+2, 1):
            self.matrix[1][i] = 0.3


    # reset a probability matrix to the initial state
    def __call__(self, x = 5, y = 8):
        """ Reset a matrix with the given dimensions to the initial state. """

        self.matrix = [[0.0 for col in range(x+2)] for row in range(y)]
        for i in range(2,len(self.matrix)):
            for j in range(1,len(self.matrix[i])-1):
                self.matrix[i][j] = 1.0/x
        self.matrix[0][(x+2)/2] = 1.0
        for i in range((x+2)/2-1, (x+2)/2+2, 1):
            self.matrix[1][i] = 0.3


# setters, getters

    # get the matrix
    def getMatrix(self):
        return self.matrix

    # set the matrix to a specified matrix - NOT CHECKING!!!
    def setMatrix(self, preset_matrix):
        self.matrix = preset_matrix[:]

    # get a specified matrix item
    def getMatrixItem(self, x, y):
        return self.matrix[x][y]

    # set a specified matrix item to a value
    def setMatrixItem(self, x, y, value):
        self.matrix[x][y] = value

# end of setters, getters


    def rescale(self, line = -1):
        """ Rescale the whole matrix, or one of the rows."""

        if line == -1:
            # we rescale the whole matrix
            for act in self.matrix:
                # get the minimum value of the current row and add a small value to it
                minimum = abs(min(act)) + MINFLOAT
                # add this to every element in the act. row
                for i in range(1,len(act)-1):
                    if not act[i] == 0.0:
                        act[i] = act[i] + minimum
                # get the total value in the row...
                summa = sum(act)
                # and divide every element by this total value
                for i in range(1,len(act)-1):
                    act[i] = act[i]/summa
        else:
            # we rescale a row
            act = self.matrix[line]
            # get the minimum value of the row and add a small value to it
            minimum = abs(min(act)) + MINFLOAT
            # add this to every element in the row
            for i in range(1,len(act)-1):
                if not act[i] == 0.0:
                    act[i] = act[i] + minimum
            # get the total value in the row...
            summa = sum(act)
            # and divide every element by this total value
            for i in range(1,len(act)-1):
                act[i] = act[i]/summa


    # log the matrix in a useable form
    def logMatrix(self, logFileName):
        """ Log the values of the matrix to the specified file."""

        try:
            logFile = open(logFileName, 'w')
        except:
            print "Can't write to", logFileName, "!"
            raise
        logFile.write("x; y; value\n")
        for i in range(0, len(self.matrix)):
            for j in range(0, len(self.matrix[i])):
                logFile.write(str(i) + '; ' + str(j) + '; ' + str(self.matrix[i][j]) + '\n')
        logFile.close()


In [176]:
class NProbMat(object):

    def __init__(self, x=5, y=8):
        self.init_mat(x, y)
        
    def init_mat(self, x, y):
        matrix = np.ones((y, x+2))
        matrix[:, 0] = 0.
        matrix[:, -1] = 0.
        for row, width in enumerate(range(1, x, 2)):
            matrix[row, 0:(x+2 - width) / 2] = 0.
            matrix[row, (x+2 - width) / 2 + width:-1] = 0.
        
        self.matrix = self.scale(matrix)

    def scale(self, matrix):
        if len(matrix.shape) == 1:
            matrix = matrix.reshape(1, len(matrix))
        sums = matrix.sum(axis=1)[:, np.newaxis]
        return matrix / sums
    
    def scale_line(self, line):
        line = self.matrix[line, :]
        line = self.scale(line)
        return self
    
    def export(self, filename):
        np.save(filename, self.matrix)
        
    def __str__(self):
        return str(self.matrix)
    
    def __repr__(self):
        return repr(self.matrix)
    
    def __getitem__(self, attr):
        return self.matrix.__getitem__(attr)

In [177]:
m = NProbMat()

In [181]:
m[:, 1]

array([ 0. ,  0. ,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2])

In [145]:
print m

TypeError: __str__ returned non-string (type numpy.ndarray)

In [124]:
matrix.matrix[1, :]

array([ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.33333333,
        0.        ,  0.        ])

In [105]:
def weighted_choice_sub(weights):
    rnd = random.random() * sum(weights)
    for i, w in enumerate(weights):
        rnd -= w
        if rnd < 0:
            return i

In [ ]:
np.random.choice(array, p=probabilities)

In [94]:
np.save('tmp.npy', mymat.matrix)

In [117]:
line = mymat.matrix[1, :]
line.reshape((1, len(line)))

array([[ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.33333333,
         0.        ,  0.        ]])

In [118]:
mymat.matrix[1, :] = line.reshape((1, len(line)))

In [119]:
mymat.matrix

array([[ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.33333333,  0.33333333,  0.33333333,
         0.        ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ],
       [ 0.        ,  0.2       ,  0.2       ,  0.2       ,  0.2       ,
         0.2       ,  0.        ]])

In [114]:
len(mymat.matrix[1, :].shape)

1

In [76]:
mymat = MyMat()

In [20]:
probmat = ProbMat()

In [21]:
probmat.matrix

[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.3, 0.3, 0.3, 0.0, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0],
 [0.0, 0.2, 0.2, 0.2, 0.2, 0.2, 0.0]]

In [22]:
mymat.matrix

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [8]:
np.array([[0.0 for col in range(5+2)] for row in range(8)])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])